package com.arzoovaswani.springgen.zip;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

public class ZipExtractor {

    public void extract(Path zipFile,
                        Path destinationDirectory)
            throws IOException {

        Files.createDirectories(destinationDirectory);

        try (InputStream inputStream = Files.newInputStream(zipFile);
             ZipInputStream zipInputStream =
                     new ZipInputStream(new BufferedInputStream(inputStream))) {

            ZipEntry entry;

            while ((entry = zipInputStream.getNextEntry()) != null) {

                String entryName = removeRootDirectory(entry.getName());

                if (entryName.isBlank()) {
                    zipInputStream.closeEntry();
                    continue;
                }

                Path outputPath = destinationDirectory
                        .resolve(entryName)
                        .normalize();

                /*
                 * Prevent Zip Slip attack.
                 */
                if (!outputPath.startsWith(destinationDirectory)) {
                    throw new IOException(
                            "Invalid ZIP entry: " + entry.getName()
                    );
                }

                if (entry.isDirectory()) {

                    Files.createDirectories(outputPath);

                } else {

                    Files.createDirectories(outputPath.getParent());

                    Files.copy(
                            zipInputStream,
                            outputPath,
                            StandardCopyOption.REPLACE_EXISTING
                    );

                }

                zipInputStream.closeEntry();

            }

        }

    }

    /**
     * Removes the root folder generated by Spring Initializr.
     *
     * expense-tracker/src/main
     *
     * becomes
     *
     * src/main
     */
    private String removeRootDirectory(String entryName) {

        int index = entryName.indexOf('/');

        if (index == -1) {
            return "";
        }

        return entryName.substring(index + 1);

    }

}